### ISSUE TITLE
ReferenceError: TechlahomaTab is not defined

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/techlahoma_shared#1]
Off to a great start! I like the simple tab API; now just need to fill it in. :wink: I.e., when I copy-pasted the "All in one embed script" from http://shared.techlahoma.org/#/techlahoma-tab, I got this error:
```
ReferenceError: TechlahomaTab is not defined
```
Because http://shared.techlahoma.org/shared/techlahoma-tab.js is 404.

**Comment by jagthedrummer** [comment]
Geez, maybe I should put the notice about "Documentation Driven Development" on every page.</sarcasm> :wink: :heart:

**Comment by jagthedrummer** [comment]
OK, the all in one code should be working now. Note that the embed code itself has changed slightly.

```javascript
  <script src="http://shared.techlahoma.org/shared/TechlahomaTab.js">
  </script>
  <script type="text/javascript">
    TechlahomaTab.init();
  </script>
```

**Comment by groovecoder** [comment]
I saw the notice, but I figured that documentation-driven development is a first step to user-submitted-issues-driven development. :smile:

**Comment by groovecoder** [comment]
Yay! It works! http://groovecoder.com/

**Comment by jagthedrummer** [comment]
:smiley:

**Comment by the-simian** [comment]
I just checked it out on Luke's site. Rad.

**Comment by amandaharlin** [comment]
sooooooo sweet! :sparkles: :sparkling_heart: :sparkles:

**Comment by jagthedrummer** [comment]
:smiley_cat:
