### ISSUE TITLE
Liberate the Techlahoma tab

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/techlahoma_shared#4]
We should liberate the Techlahoma tab into its own repository with an easy README for sites to add it.

**Comment by amandaharlin** [comment]
this is a great idea! i'll make that repo right now.

**Comment by amandaharlin** [comment]
added the tab widget code to here https://github.com/techlahoma/techlahoma-tab

the code is still in this repo. didn't want to change it without giving the shared styles team a heads up.

**Comment by vlucas** [comment]
TABlahoma! :)

**Comment by DevinClark** [comment]
@vlucas :+1:

**Comment by the-simian** [comment]
Its free!
